markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

destination: _site

# SEO settings
url: http://isir-ecom.github.io
baseurl: ""
# baseurl: ""


# Author settings
author:
  name      : Vachik Dave
  url       : https://www.linkedin.com/in/vachik-dave


# Site settings
title: ISIR-eCom
# email: your-email@domain.com
description: "The first international workshop on Interactive and Scalable Information Retrieval methods for eCommerce."

# Build settings
# permalink: pretty
theme: jekyll-theme-minimal


# Team names, titles and social links
people:
- name: Vachik Dave
  pic: 1
  position: Walmart Global Tech
  url: https://www.linkedin.com/in/vachik-dave

- name: Linsey Pang
  pic: 2
  position: Walmart Global Tech
  url: https://www.linkedin.com/in/linsey-pang

- name: Xiquan Cui
  pic: 3
  position: The Home Depot
  url: https://www.linkedin.com/in/xiquan-cui

- name: Lingfei Wu
  pic: 4
  position: JD.COM Silicon Valley Research Center
  url: https://sites.google.com/a/email.wm.edu/teddy-lfwu/

- name: Hamed Zamani
  pic: 5
  position: University of Massachusetts Amherst
  url: http://cs.umass.edu/~zamani

- name: George Karypis
  pic: 6
  position: University of Minnesota Twint-cities
  url: http://glaros.dtc.umn.edu/


